name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flask aiofiles aiohttp google-api-python-client

    - name: Run Pylint and check score
      id: pylint
      run: |
        pylint_output=$(pylint $(git ls-files '*.py') | tee pylint-report.txt)
        pylint_score=$(tail -n 2 pylint-report.txt | grep "Your code has been rated" | awk '{print $7}' | cut -d '/' -f 1)
        echo "Pylint score is $pylint_score"
        if (( $(echo "$pylint_score < 7.0" | bc -l) )); then
          echo "Pylint score is below 7.0, failing the build."
          exit 1
        fi
